---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Always exclude files that are updated by Home Assistant
exclude: '^(custom_components/|www/|\.HA_VERSION)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Fixes
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

      # Checks
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe] # Allow HA YAML extensions
