default_config:

homeassistant:
  packages: !include_dir_named packages

frontend: !include frontend.yaml

group: !include groups.yaml
automation: !include automations.yaml
automation yaml: !include_dir_merge_list automations
script: !include scripts.yaml
script yaml: !include_dir_merge_named scripts
scene: !include scenes.yaml
scene yaml: !include_dir_merge_list scenes
template: !include_dir_merge_list templates

panel_custom: !include panel_custom.yaml

logbook: !include logbook.yaml
logger: !include logger.yaml
recorder: !include recorder.yaml
system_log: !include system_log.yaml

wake_on_lan:

websocket_api:
