---
#-
# frontend automations
#- from https://github.com/igetgames/home-assistant-configuration

- alias: "Frontend: Change theme"
  trigger:
    - platform: state
      entity_id: input_select.theme
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: >
        {% set name = states("input_select.theme") -%}
        {{ name }}

