---
homeassistant:
  customize:
    alert.bluetooth_offline:
      icon: mdi:bluetooth-off
      category: bluetooth

    device_tracker.amazfit_gts_2_mini_ble:
      device_type: bluetooth_le
      name: Amazfit GTS 2 mini (BLE)
    device_tracker.amazfit_t_rex_pro_ble:
      device_type: bluetooth_le
      name: Amazfit T-Rex Pro (BLE)
    device_tracker.b06_plus_bt:
      device_type: bluetooth
    device_tracker.jbl_charge_5_ble:
      device_type: bluetooth_le
      name: JBL Charge 5 (BLE)
    device_tracker.marcus_iphone_bt:
      device_type: bluetooth
    device_tracker.thingy_one_ble:
      device_type: bluetooth_le
      name: Thingy:52 One (BLE)
    device_tracker.triones_ffff140345ba_ble:
      device_type: bluetooth_le
      name: Triones 140345BA (BLE)
    device_tracker.triones_ffff9104f633_ble:
      device_type: bluetooth_le
      name: Triones 9104F633 (BLE)

ble_monitor:
  active_scan: true
  bt_auto_restart: true
  bt_interface: !secret ble_monitor_bt_interfaces
  devices: !secret ble_monitor_devices
  discovery: false

alert:
  bluetooth_offline:
    name: Bluetooth Offline
    title: Bluetooth Offline
    message: Home Assistant Bluetooth is not running.
    done_message: clear_notification
    entity_id: binary_sensor.bluetooth_offline_alert
    state: 'on'
    repeat: 3600
    # notifiers:
    data:
      tag: bluetooth_offline
      group: System
      channel: Alert
      importance: max
      ttl: 0
      priority: high
      visibility: public
      notification_icon: mdi:bluetooth
      clickAction: /lovelace/system
      actions:
        - action: reboot_server
          title: Reboot

template:
  - sensor:
      - name: Bluetooth Devices
        unique_id: bluetooth_devices
        icon: mdi:bluetooth-settings
        unit_of_measurement: devices
        state: >
          {% set c = state_attr(this.entity_id,'entity_id') %}
          {{ c|count if c != none else none }}
        attributes:
          entity_id: >
            {{ states.device_tracker|selectattr('attributes.device_type','eq','bluetooth')|map(attribute='entity_id')|list }}

      - name: Bluetooth LE Devices
        unique_id: bluetooth_le_devices
        icon: mdi:bluetooth-settings
        unit_of_measurement: devices
        state: >
          {% set c = state_attr(this.entity_id,'entity_id') %}
          {{ c|count if c != none else none }}
        attributes:
          entity_id: >
            {{ states.device_tracker | selectattr('attributes.device_type','eq','bluetooth_le')|map(attribute='entity_id')|list }}
