---
homeassistant:
  customize:
    lock.front_door_lock:
      device_class: lock
      area: house
      friendly_name: 'Front Door Lock'
      type: entry
    lock.front_door_lock_remote:
      device_class: lock
      area: house
      friendly_name: 'Front Door Lock (Remote)'
      type: entry

input_text:
  front_door_lock_status:
    name: 'Front Door Lock Status'
    icon: mdi:lock
