---
# Renovate this repository if Renovate-specific tasks are checked or if dispatched.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  renovate:
    if: >-
      (github.event_name != 'issues' && github.event_name != 'pull_request') ||
      (
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-all-pending-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approvePr-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- create-all-rate-limited-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- manual job -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- other-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-all-open-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-check -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- recreate-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- retry-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unlimit-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unschedule-branch=')
      )
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: filter
        if: github.event_name == 'push'
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          filters: |
            changes:
              - '.github/workflows/renovate.yaml'
              - '.github/renovate.json5'
      - if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Renovate
        uses: bfra-me/renovate-action@433da0928380032ddb82c2cba06d0886be9fb31e # v2.7.28
        with:
          branch: ${{ github.ref != 'refs/heads/main' && github.ref_name || '' }}
          cache: >-
            ${{ contains('["push", "workflow_dispatch"]', github.event_name) && github.ref == 'refs/heads/main' || startsWith(github.ref_name, 'renovate/') }}
          dry_run: ${{ github.event_name == 'push' && !contains('["main", "renovate/reconfigure"]', github.ref_name) }}
          print_config: ${{ inputs.print_config }}
          renovate_app_id: ${{ secrets.APPLICATION_ID }}
          renovate_app_pem: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          renovate_app_slug: 'mrbro-bot'
